language: objective-c
xcode_workspace: Example/Example.xcworkspace
xcode_scheme: Example
xcode_sdk: iphonesimulator7.1
env: CODE_SIGN_IDENTITY=- CODE_SIGNING_REQUIRED=NO
notifications:
  email: false

install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail && xcodebuild test -workspace Example/FSSyncSpinner.xcworkspace -scheme FSSyncSpinner-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
- pod lib lint --quick
